#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/properties-management-system
#    username: postgres
#    password: LisaPostgres
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update   #i changed this to auto
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#
#    flyway:
#      enabled: true
#      locations: classpath:db/migration
#
#  # Server config (must be top-level)
#  server:
#    port: 8081
#
#  # Logging config (must be top-level)
#  logging:
#    level:
#      root: INFO
#      org.hibernate.SQL: DEBUG
#


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/properties-management-system
    username: postgres
    password: LisaPostgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8081


logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
